/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateOffersRouteImport } from './routes/private-offers'
import { Route as MyOffersRouteImport } from './routes/my-offers'
import { Route as HistoricRouteImport } from './routes/historic'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfferIdRouteImport } from './routes/offer/$id'

const PrivateOffersRoute = PrivateOffersRouteImport.update({
  id: '/private-offers',
  path: '/private-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOffersRoute = MyOffersRouteImport.update({
  id: '/my-offers',
  path: '/my-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricRoute = HistoricRouteImport.update({
  id: '/historic',
  path: '/historic',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferIdRoute = OfferIdRouteImport.update({
  id: '/offer/$id',
  path: '/offer/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/historic': typeof HistoricRoute
  '/my-offers': typeof MyOffersRoute
  '/private-offers': typeof PrivateOffersRoute
  '/offer/$id': typeof OfferIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/historic': typeof HistoricRoute
  '/my-offers': typeof MyOffersRoute
  '/private-offers': typeof PrivateOffersRoute
  '/offer/$id': typeof OfferIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/historic': typeof HistoricRoute
  '/my-offers': typeof MyOffersRoute
  '/private-offers': typeof PrivateOffersRoute
  '/offer/$id': typeof OfferIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faq'
    | '/historic'
    | '/my-offers'
    | '/private-offers'
    | '/offer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faq'
    | '/historic'
    | '/my-offers'
    | '/private-offers'
    | '/offer/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faq'
    | '/historic'
    | '/my-offers'
    | '/private-offers'
    | '/offer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FaqRoute: typeof FaqRoute
  HistoricRoute: typeof HistoricRoute
  MyOffersRoute: typeof MyOffersRoute
  PrivateOffersRoute: typeof PrivateOffersRoute
  OfferIdRoute: typeof OfferIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/private-offers': {
      id: '/private-offers'
      path: '/private-offers'
      fullPath: '/private-offers'
      preLoaderRoute: typeof PrivateOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-offers': {
      id: '/my-offers'
      path: '/my-offers'
      fullPath: '/my-offers'
      preLoaderRoute: typeof MyOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historic': {
      id: '/historic'
      path: '/historic'
      fullPath: '/historic'
      preLoaderRoute: typeof HistoricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/$id': {
      id: '/offer/$id'
      path: '/offer/$id'
      fullPath: '/offer/$id'
      preLoaderRoute: typeof OfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FaqRoute: FaqRoute,
  HistoricRoute: HistoricRoute,
  MyOffersRoute: MyOffersRoute,
  PrivateOffersRoute: PrivateOffersRoute,
  OfferIdRoute: OfferIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
